#define NUMBER_OF_SEQUENCERS 6
#define MAX_SEQUENCER_STEPS 32
#define NUMBER_OF_VOLTAGE_RANGES 8
#define NUMBER_OF_SNAP_DIVISIONS 8

// Constants for patterns
#define DRAW_AREA_WIDTH 486.0
#define DRAW_AREA_HEIGHT 206.0
#define BAR_HEIGHT 214.0
#define BAR_HORIZONTAL_PADDING .8
#define DRAW_AREA_POSITION_X 9
#define DRAW_AREA_POSITION_Y 9.5

#define MINI_MAP_POSITION_X 5.5
#define MINI_MAP_POSITION_Y 84.3
#define MINI_MAP_DRAW_AREA_WIDTH 506.0
#define MINI_MAP_DRAW_AREA_HEIGHT 32.1
#define MINI_MAP_MULTIPLIER 32.0
#define MINI_MAP_WINDOW_BOX_WIDTH 32.0

#define TOOLTIP_WIDTH 33.0
#define TOOLTIP_HEIGHT 20.0
